language: generic 
sudo: required

services:
    - docker

before_install:
    - docker build -t ucoruh/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true ucoruh/react-test npm test 

after_success:
    - docker build -t ucoruh/multi-client ./client
    - docker build -t ucoruh/multi-nginx ./nginx
    - docker build -t ucoruh/multi-server ./server
    - docker build -t ucoruh/multi-worker ./worker
    # Log in to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push ucoruh/multi-client
    - docker push ucoruh/multi-nginx
    - docker push ucoruh/multi-server
    - docker push ucoruh/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-us-east-2-883636570212"
    bucket_path: "docker-multi"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY